# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H1ObmalxQSLgg2cOXids7zH1qEssvhKv
"""

import pandas as pd
import numpy as np
import streamlit as st

# ---------- КРИТЕРИИ ----------

def compute_efficacy(df, group_means_df, group_col, deficit_groups, normal_groups, effect_markers):
    deficit_mask = df[group_col].isin(deficit_groups)
    normal_mask = df[group_col].isin(normal_groups)

    E_list = []

    for marker in effect_markers:
        if marker not in group_means_df.columns:
            continue

        E_plus = df.loc[deficit_mask, marker].mean()
        E_minus = df.loc[normal_mask, marker].mean()

        if pd.isna(E_plus) or pd.isna(E_minus) or np.isclose(E_plus, E_minus):
            continue

        E_d = group_means_df[marker]
        R_d = (E_d - E_plus) / (E_minus - E_plus)

        Eff = pd.Series(index=group_means_df.index, dtype=float)
        for d in group_means_df.index:
            R = R_d.loc[d]
            if R <= 0:
                Eff.loc[d] = 0.0
            elif 0 < R <= 1:
                Eff.loc[d] = R
            elif 1 < R < 2:
                Eff.loc[d] = 2 - R
            else:
                Eff.loc[d] = 0.0

        if Eff.max() > 0:
            Eff = Eff / Eff.max()
        E_list.append(Eff)

    if not E_list:
        return pd.Series(0.0, index=group_means_df.index)

    E_mean = pd.concat(E_list, axis=1).mean(axis=1)
    return E_mean


def compute_toxicity(group_means_df, toxic_markers):
    used = [m for m in toxic_markers if m in group_means_df.columns]
    if not used:
        return pd.Series(0.0, index=group_means_df.index)

    if 0.0 not in group_means_df.index:
        # нет дозы 0 как контроля – вернём нули
        return pd.Series(0.0, index=group_means_df.index)

    control = group_means_df.loc[0.0]

    Toxic_raw = pd.Series(0.0, index=group_means_df.index, dtype=float)

    for m in used:
        T_minus = control[m]
        for d in group_means_df.index:
            T_d = group_means_df.loc[d, m]
            if T_minus == 0 or pd.isna(T_minus) or pd.isna(T_d):
                delta = 0.0
            else:
                delta = (T_d - T_minus) / T_minus
                if delta < 0:
                    delta = 0.0
            Toxic_raw.loc[d] += delta

    Toxic_raw = Toxic_raw / len(used)

    max_val = Toxic_raw.max()
    if max_val > 0:
        return Toxic_raw / max_val
    else:
        return pd.Series(0.0, index=group_means_df.index)


def compute_balance(group_means_df, balance_markers):
    used = [m for m in balance_markers if m in group_means_df.columns]
    if not used:
        return pd.Series(1.0, index=group_means_df.index)

    if 0.0 not in group_means_df.index:
        return pd.Series(1.0, index=group_means_df.index)

    control = group_means_df.loc[0.0]

    D = pd.Series(0.0, index=group_means_df.index, dtype=float)
    for d in group_means_df.index:
        vals = []
        for m in used:
            Xd = group_means_df.loc[d, m]
            Xminus = control[m]
            if Xminus == 0 or pd.isna(Xminus) or pd.isna(Xd):
                continue
            vals.append(abs((Xd - Xminus) / Xminus))
        D.loc[d] = np.mean(vals) if vals else 0.0

    max_D = D.max()
    if max_D > 0:
        return 1 - D / max_D
    else:
        return pd.Series(1.0, index=group_means_df.index)


def compute_score(efficacy, balance, toxicity, w_e, w_b, w_t):
    s = w_e + w_b + w_t
    if s == 0:
        w_e, w_b, w_t = 1.0, 0.0, 0.0
    else:
        w_e, w_b, w_t = w_e / s, w_b / s, w_t / s
    return w_e * efficacy + w_b * balance - w_t * toxicity


# ---------- STREAMLIT UI ----------

st.title("Анализ дозозависимых эффектов и расчёт Score")

st.write("Загрузите CSV с данными (например, Rats_lastclear4.csv).")

uploaded = st.file_uploader("Файл CSV", type=["csv"])

if uploaded is not None:
    df = pd.read_csv(uploaded, sep=';', decimal=',')
    st.write("Первые строки данных:")
    st.dataframe(df.head())

    # выбор столбца с группами
    group_col = st.selectbox(
        "Столбец с названиями групп",
        options=df.columns.tolist(),
        index=df.columns.tolist().index("Группа") if "Группа" in df.columns else 0
    )

    # уникальные группы
    groups = df[group_col].unique().tolist()
    st.write("Найденные группы:", groups)

    # выбор групп дефицита и нормы
    deficit_groups = st.multiselect(
        "Группы дефицита/болезни",
        options=groups,
        default=[g for g in groups if "дефицит" in str(g).lower()]
    )
    normal_groups = st.multiselect(
        "Группы нормы",
        options=groups,
        default=[g for g in groups if "Отрицательный контроль" in str(g)]
    )

    # выбор столбца/столбцов с дозой
    st.write("Если в данных уже есть числовой столбец с дозой, выберите его.")
    dose_col_option = st.selectbox(
        "Столбец с дозой (или 'Создать из групп')",
        options=["Создать из групп"] + list(df.columns)
    )

    # если дозы создаём из групп – нужен маппинг
    if dose_col_option == "Создать из групп":
        st.write("Создаём дозу по группам. Укажите соответствие (группа → доза).")
        dose_map = {}
        for g in groups:
            val = st.text_input(f"Доза для группы '{g}' (пусто = исключить)", "")
            if val.strip() == "":
                dose_map[g] = np.nan
            else:
                try:
                    dose_map[g] = float(val.replace(",", "."))
                except ValueError:
                    dose_map[g] = np.nan
        df["dose"] = df[group_col].map(dose_map)
    else:
        df["dose"] = pd.to_numeric(df[dose_col_option], errors="coerce")

    df = df[~df["dose"].isna()].copy()

    st.write("Распределение доз:")
    st.write(df["dose"].value_counts().sort_index())

    # выбор маркеров
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    # удалим служебные столбцы
    if "dose" in numeric_cols:
        numeric_cols.remove("dose")

    effect_markers = st.multiselect(
        "Маркеры эффективности",
        options=numeric_cols,
        default=[c for c in numeric_cols if "Zn_blood" in c] or []
    )

    toxic_markers = st.multiselect(
        "Маркеры токсичности",
        options=numeric_cols,
        default=[c for c in numeric_cols if c in ["As_liver", "Pb_kidneys", "Cu_liver"]]
    )

    balance_markers = st.multiselect(
        "Маркеры баланса (обычно Zn по органам)",
        options=numeric_cols,
        default=[c for c in numeric_cols if c.startswith("Zn_")]
    )

    # веса
    st.write("Веса критериев (сумма будет автоматически нормирована):")
    w_e = st.number_input("w_e (эффективность)", min_value=0.0, max_value=1.0, value=0.6, step=0.05)
    w_b = st.number_input("w_b (баланс)", min_value=0.0, max_value=1.0, value=0.2, step=0.05)
    w_t = st.number_input("w_t (токсичность)", min_value=0.0, max_value=1.0, value=0.2, step=0.05)

    if st.button("Рассчитать Score"):
        # групповые средние
        cols_for_means = list(set(effect_markers + toxic_markers + balance_markers))
        gmeans = df.groupby("dose")[cols_for_means].mean()

        eff = compute_efficacy(
            df, gmeans,
            group_col=group_col,
            deficit_groups=deficit_groups,
            normal_groups=normal_groups,
            effect_markers=effect_markers
        )
        tox = compute_toxicity(gmeans, toxic_markers)
        bal = compute_balance(gmeans, balance_markers)

        score = compute_score(eff, bal, tox, w_e, w_b, w_t)

        res = pd.DataFrame({
            "dose": gmeans.index,
            "Efficacy": eff.values,
            "Balance": bal.values,
            "Toxicity": tox.values,
            "Score": score.values
        }).set_index("dose")

        st.subheader("Результат по дозам")
        st.dataframe(res.sort_values("Score", ascending=False))

        # скачать
        csv_bytes = res.to_csv().encode("utf-8")
        st.download_button(
            label="Скачать результаты в CSV",
            data=csv_bytes,
            file_name="dose_scores.csv",
            mime="text/csv"
        )