# -*- coding: utf-8 -*-
"""app0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12lXqTcqqVOAh89tG8qyIqiyWkdQK1n-d
"""

import streamlit as st
import pandas as pd
import numpy as np
from scipy import stats
import statsmodels.api as sm

st.title("Dose-response analysis module")

st.write(
    "Загрузите CSV с данными (строки — животные, столбцы — признаки). "
    "Нужен столбец с группами и/или дозой."
)

uploaded = st.file_uploader("Файл CSV", type=["csv"])

if uploaded is not None:
    # --- загрузка данных ---
    df = pd.read_csv(uploaded, sep=';', decimal=',')
    st.subheader("Первые строки данных")
    st.dataframe(df.head())

    # --- выбор столбца с группами и дозой ---
    cols = df.columns.tolist()

    group_col = st.selectbox(
        "Столбец с названиями групп (если есть)",
        options=["(нет)"] + cols,
        index=(cols.index("Группа") + 1) if "Группа" in cols else 0
    )

    dose_mode = st.radio(
        "Как задать дозу?",
        ["Числовой столбец дозы", "Сопоставить дозу по названию группы"]
    )

    if dose_mode == "Числовой столбец дозы":
        dose_col = st.selectbox(
            "Столбец с дозой",
            options=cols
        )
        df["__dose__"] = pd.to_numeric(df[dose_col], errors="coerce")
    else:
        if group_col == "(нет)":
            st.error("Для этого режима нужен столбец групп.")
            st.stop()
        st.write("Укажите дозу для каждой группы (пусто = исключить из анализа).")
        dose_map = {}
        for g in df[group_col].unique():
            val = st.text_input(f"Доза для группы '{g}'", "")
            if val.strip() == "":
                dose_map[g] = np.nan
            else:
                try:
                    dose_map[g] = float(val.replace(",", "."))
                except ValueError:
                    dose_map[g] = np.nan
        df["__dose__"] = df[group_col].map(dose_map)

    # выбрасываем строки без дозы
    df = df[~df["__dose__"].isna()].copy()
    st.write("Распределение доз:")
    st.write(df["__dose__"].value_counts().sort_index())

    # --- выбор числовых признаков для анализа ---
    num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    if "__dose__" in num_cols:
        num_cols.remove("__dose__")
    st.write("Числовые признаки, доступные для анализа:")
    st.write(num_cols)

    selected_cols = st.multiselect(
        "Какие признаки анализировать? (если пусто — все)",
        options=num_cols,
        default=[]
    )
    if not selected_cols:
        selected_cols = num_cols

    # --- пороги значимости ---
    st.subheader("Пороги отбора dose-responsive маркеров")
    alpha_kw = st.number_input("α для Kruskal–Wallis (межгрупповые различия)", 0.0, 1.0, 0.05, 0.01)
    alpha_sp = st.number_input("α для Spearman (монотонный тренд)", 0.0, 1.0, 0.05, 0.01)
    alpha_quad = st.number_input("α для квадратичного члена (нелинейность)", 0.0, 1.0, 0.05, 0.01)

    if st.button("Запустить анализ дозозависимости"):
        results = []

        # подготовим массив доз и группы для Kruskal-Wallis
        doses = df["__dose__"].values

        for col in selected_cols:
            y = df[col].values

            # --- Kruskal–Wallis по группам доз ---
            # разбиваем на группы по значениям __dose__
            groups = []
            for d in np.sort(df["__dose__"].unique()):
                groups.append(df.loc[df["__dose__"] == d, col].values)
            try:
                H, p_kw = stats.kruskal(*groups)
            except ValueError:
                # если только одна группа или ещё какая проблема
                H, p_kw = np.nan, np.nan

            # --- Spearman ---
            try:
                rho, p_sp = stats.spearmanr(doses, y, nan_policy="omit")
            except Exception:
                rho, p_sp = np.nan, np.nan

            # --- линейно-квадратичная регрессия ---
            # модель y = b0 + b1*d + b2*d^2
            try:
                X = np.column_stack([doses, doses**2])
                X = sm.add_constant(X)
                model = sm.OLS(y, X, missing="drop").fit()
                # коэффициенты: const, d, d^2
                b0, b1, b2 = model.params
                p_const, p_lin, p_quad = model.pvalues
            except Exception:
                b0 = b1 = b2 = np.nan
                p_lin = p_quad = np.nan

            # --- флаг dose-responsive ---
            dose_resp = (
                (not np.isnan(p_kw) and p_kw < alpha_kw) or
                (not np.isnan(p_sp) and p_sp < alpha_sp) or
                (not np.isnan(p_quad) and p_quad < alpha_quad)
            )

            results.append({
                "marker": col,
                "H_kw": H,
                "p_kw": p_kw,
                "rho_spearman": rho,
                "p_spearman": p_sp,
                "beta_lin": b1,
                "beta_quad": b2,
                "p_lin": p_lin,
                "p_quad": p_quad,
                "dose_responsive": dose_resp
            })

        res_df = pd.DataFrame(results)
        st.subheader("Результаты анализа (все маркеры)")
        st.dataframe(res_df)

        st.subheader("Dose-responsive маркеры (по заданным порогам)")
        st.dataframe(res_df[res_df["dose_responsive"]].sort_values("p_kw"))

        # кнопка загрузки
        csv_bytes = res_df.to_csv(index=False).encode("utf-8")
        st.download_button(
            label="Скачать результаты в CSV",
            data=csv_bytes,
            file_name="dose_response_results.csv",
            mime="text/csv"
        )
else:
    st.info("Пожалуйста, загрузите CSV-файл.")